[project]
name = "ai-programming"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cowsay>=6.1",
    "matplotlib>=3.10.7",
    "requests>=2.32.5",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
